# Auto-generated by rules_remotivelabs
# remotive-topology {version} ({platform})
#
# The outer wrapper (remotive_topology/bin/remotive-topology) sets LD_LIBRARY_PATH
# and execs the OTP shell script. All files under remotive_topology/ are declared
# as data so the runfiles tree preserves the expected layout (ERTS wrappers find
# the bundled musl interpreter and libgcc_s.so.1 by relative path).
#
# Toolchain registration (with platform constraints) lives in the
# `@remotivelabs_topology_toolchains` hub repo, not here.

load("@rules_remotivelabs//remotivelabs/toolchains/remotive_topology:defs.bzl", "remotive_topology_toolchain")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

# `topology` rather than `remotive_topology` so the launcher name doesn't
# clash with the `remotive_topology/` release directory in the runfiles tree.
sh_binary(
    name = "topology",
    srcs = ["topology_bazel_shim.sh"],
    data = glob(["remotive_topology/**"]),
    visibility = ["//visibility:public"],
)

# Toolchain wrapper consumed by the hub repo's `toolchain(...)` declarations.
remotive_topology_toolchain(
    name = "toolchain_impl",
    binary = ":topology",
    visibility = ["//visibility:public"],
)
