# Auto-generated by rules_remotivelabs.
#
# Toolchain registrations for every (version, platform) requested by the
# dep graph. `register_toolchains("@remotivelabs_topology_toolchains//:all")`
# in the rules' own MODULE.bazel propagates these globally so consumers
# don't need to do their own registration.

{toolchains}
